# .github/workflows/reusable.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:  #👈 These are called **Inputs** (Passed by the caller to control behavior)
      environment:
        required: true
        type: string
    secrets: #👈 These are called **Secrets** (Passed securely by the caller (like tokens))
      DEPLOY_TOKEN:
        required: true
    outputs: #👈 These are called **Workflow Outputs** (Returned by this workflow to the caller)
      result:
        description: "Result of example job"
        value: ${{ jobs.example.outputs.result }}

jobs:
  example:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.step1.outputs.result }}
    steps:
      - id: step1
        run: |
          echo "result=WHY NOT?  ${{ inputs.environment }}" >> $GITHUB_OUTPUT
