# .github/workflows/reusable.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      DEPLOY_TOKEN:
        required: true
    outputs:
      result:
        description: "Result of example job"
        value: ${{ jobs.example.outputs.result }}

jobs:
  example:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.step1.outputs.result }}
    steps:
      - id: step1
        run: |
          echo "result=WHY YOU SUCKING D?" >> $GITHUB_OUTPUT
