name: Check Label if Bug

on:
 issues:
    types:
    - labeled
    - closed
 pull_request:
    types:
    - closed
  
jobs:
    run_if_label_matches:
      runs-on: ubuntu-latest
      steps:
      - name: if_labelled_as_bug
        if: github.event.label.name == 'bug'
        run: echo 'The label was bug'

      - name: if_issue
        if: github.event.issue
        run: |
          echo An issue was closed
          
      - name: if_pr
        if: github.event.pull_request
        run: |
          echo A pull request was closed